# Generated by Django 5.0.1 on 2024-01-04 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A1_viec_lam', '0001_initial'),
        ('chotot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Address_A1', to='chotot.address', verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='job',
            name='Career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Career_A1', to='A1_viec_lam.career', verbose_name='Nghành nghề'),
        ),
        migrations.AddField(
            model_name='job',
            name='Experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Experience_A1', to='A1_viec_lam.experience', verbose_name='Kinh nghiệm'),
        ),
        migrations.AddField(
            model_name='job',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Location_A1', to='chotot.location', verbose_name='Khu vực'),
        ),
        migrations.AddField(
            model_name='job',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_User_A1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job_image',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_image_Job_A1', to='A1_viec_lam.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='Pay_forms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Pay_forms_A1', to='A1_viec_lam.pay_forms', verbose_name='Hình thức trả lương'),
        ),
        migrations.AddField(
            model_name='job',
            name='Sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Sex_A1', to='A1_viec_lam.sex', verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='job',
            name='Type_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Type_of_work_A1', to='A1_viec_lam.type_of_work', verbose_name='Loại công việc'),
        ),
    ]
