# Generated by Django 5.0 on 2024-01-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B3_dich_vu', '0006_category_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='key',
        ),
        migrations.AddField(
            model_name='category',
            name='keyForm',
            field=models.CharField(choices=[('COMMON-SERVICE', 'COMMON-SERVICE')], default='', max_length=20, verbose_name='keyForm'),
            preserve_default=False,
        ),
    ]
