# Generated by Django 5.0 on 2024-01-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B1_xe_co', '0002_remove_category_parentcategory'),
        ('B2_do_dien_tu', '0002_remove_category_parentcategory'),
        ('B3_dich_vu', '0002_remove_category_parentcategory'),
        ('B4_do_gia_dung_noi_that', '0002_remove_category_parentcategory'),
        ('B5_cua_hang_viet', '0002_remove_category_parentcategory'),
        ('chotot', '0002_parentcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentCategory',
        ),
    ]
