# Generated by Django 5.0 on 2024-01-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chotot', '0003_delete_parentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Khu vực')),
                ('Image', models.ImageField(upload_to='chotot/Parent_Category_image')),
                ('Icon', models.FileField(upload_to='chotot/icon')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '3 - Danh mục cha',
                'ordering': ['id'],
            },
        ),
    ]
