# Generated by Django 5.0 on 2024-01-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chotot', '0004_parent_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parent_Category',
            new_name='ParentCategory',
        ),
    ]
