# Generated by Django 5.0.1 on 2024-01-04 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A5_taxi', '0001_initial'),
        ('chotot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Address_A5', to='chotot.address', verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='items',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Location_A5', to='chotot.location', verbose_name='Khu vực'),
        ),
        migrations.AddField(
            model_name='items',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_User_A5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items_image',
            name='Items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_image_Items_A5', to='A5_taxi.items'),
        ),
        migrations.AddField(
            model_name='items',
            name='Posted_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Posted_news_A5', to='A5_taxi.posted_news', verbose_name='Tin dăng'),
        ),
        migrations.AddField(
            model_name='items',
            name='Poster_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Poster_information_A5', to='A5_taxi.poster_information', verbose_name='Thông tin người đăng'),
        ),
    ]
