# Generated by Django 5.0 on 2024-01-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A5_taxi', '0003_remove_items_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Address',
        ),
    ]
