# Generated by Django 5.0.1 on 2024-01-10 08:33

import B5_cua_hang_viet.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chotot', '0002_parentcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Thông tin người bán')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '2 - Thông tin người bán',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Danh mục')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('ParentCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent_Category_B5', to='chotot.parentcategory', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name_plural': '1 - Danh mục',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Map', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí bản đồ')),
                ('Free_giveaway', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tặng miễn phí')),
                ('Price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giá')),
                ('Title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề')),
                ('Detailed_description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('Video', models.FileField(blank=True, null=True, upload_to='B5/Items_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv']), B5_cua_hang_viet.models.validate_file_size])),
                ('Contact_phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số điện thoại liên hệ')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Address_B5', to='chotot.address', verbose_name='Địa chỉ')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Category_B5', to='B5_cua_hang_viet.category', verbose_name='Danh mục')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Location_B5', to='chotot.location', verbose_name='Khu vực')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_User_B5', to=settings.AUTH_USER_MODEL)),
                ('Seller_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Seller_information_B5', to='B5_cua_hang_viet.seller_information', verbose_name='Thông tin người bán')),
            ],
            options={
                'verbose_name_plural': '3 - Sản phẩm shop việt',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Items_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='B5/Items_image')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_image_Items_B5', to='B5_cua_hang_viet.items')),
            ],
            options={
                'verbose_name_plural': '4 - Ảnh Sản phẩm',
                'ordering': ['id'],
            },
        ),
    ]
