# Generated by Django 5.0 on 2024-01-12 04:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B5_cua_hang_viet', '0002_remove_category_parentcategory'),
        ('chotot', '0003_delete_parentcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='ItemsB5',
        ),
    ]
