# Generated by Django 5.0 on 2024-01-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B5_cua_hang_viet', '0005_remove_category_parentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.CharField(choices=[('COMMON-VIETSHOP', 'COMMON-VIETSHOP')], default=1, max_length=50, verbose_name='Key'),
            preserve_default=False,
        ),
    ]
