# Generated by Django 5.0.1 on 2024-01-10 08:33

import B2_do_dien_tu.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chotot', '0002_parentcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Tình trạng sử dụng')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '5 - Dung lượng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hãng xe')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '4 - Màu sắc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hãng xe')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '3 - Hãng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên bảo hành')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '6 - Bảo hành',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hard_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Tình trạng sử dụng')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '9 - Ổ cứng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Microprocessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hãng xe')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '7 - Bộ vi xử lý',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Monitor_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên bảo hành')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '10 - Car màn hình',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hãng xe')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '8 - Ram',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Screen_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hãng xe')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '11 - kích cỡ màn hình',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Seller_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Thông tin người bán')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '12 - Thông tin người bán',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usage_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Tình trạng sử dụng')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': '2 - Tình trạng sử dụng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Danh mục')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('ParentCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent_Category_B2', to='chotot.parentcategory', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name_plural': '1 - Danh mục',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Map', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí bản đồ')),
                ('Free_giveaway', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tặng miễn phí')),
                ('Price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giá')),
                ('Title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề')),
                ('Detailed_description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('Video', models.FileField(blank=True, null=True, upload_to='B2/Items_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv']), B2_do_dien_tu.models.validate_file_size])),
                ('Contact_phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số điện thoại liên hệ')),
                ('Url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Address_B2', to='chotot.address', verbose_name='Địa chỉ')),
                ('Capacity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Capacity_B2', to='B2_do_dien_tu.capacity', verbose_name='Dung lượng')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Category_B2', to='B2_do_dien_tu.category', verbose_name='Danh mục')),
                ('Color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Color_B2', to='B2_do_dien_tu.color', verbose_name='Màu sắc')),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Company_B2', to='B2_do_dien_tu.company', verbose_name='Hãng')),
                ('Guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Guarantee_B2', to='B2_do_dien_tu.guarantee', verbose_name='Bảo hành')),
                ('Hard_drive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Hard_drive_B2', to='B2_do_dien_tu.hard_drive', verbose_name='Ổ cứng')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Location_B2', to='chotot.location', verbose_name='Khu vực')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_User_B2', to=settings.AUTH_USER_MODEL)),
                ('Microprocessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Microprocessor_B2', to='B2_do_dien_tu.microprocessor', verbose_name='Bộ vi xử lý')),
                ('Monitor_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Monitor_card_B2', to='B2_do_dien_tu.monitor_card', verbose_name='Car màn hình')),
                ('Ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Ram_B2', to='B2_do_dien_tu.ram', verbose_name='Ram')),
                ('Screen_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items_Screen_size_B2', to='B2_do_dien_tu.screen_size', verbose_name='Kích cớ màn hình')),
                ('Seller_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Seller_information_B2', to='B2_do_dien_tu.seller_information', verbose_name='Thông tin người bán')),
                ('Usage_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Usage_status_B2', to='B2_do_dien_tu.usage_status', verbose_name='Tình trạng sử dụng')),
            ],
            options={
                'verbose_name_plural': '13 - Sản phẩm bán xe cộ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Items_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='B2/Items_image')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_image_Items_B2', to='B2_do_dien_tu.items')),
            ],
            options={
                'verbose_name_plural': '12 - Ảnh Sản phẩm đồ điện tử',
                'ordering': ['id'],
            },
        ),
    ]
