# Generated by Django 5.0 on 2024-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2_do_dien_tu', '0007_alter_category_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('LAPTOP', 'LAPTOP'), ('TABLET', 'TABLET'), ('DESKTOP', 'DESKTOP'), ('COMMON-ELECTRONICE-DEVICE', 'COMMON-ELECTRONICE-DEVICE')], max_length=50, verbose_name='Key'),
        ),
    ]
