# Generated by Django 5.0 on 2024-01-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2_do_dien_tu', '0008_alter_category_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='key',
        ),
        migrations.AddField(
            model_name='category',
            name='keyForm',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('LAPTOP', 'LAPTOP'), ('TABLET', 'TABLET'), ('DESKTOP', 'DESKTOP'), ('COMMON-ELECTRONICE-DEVICE', 'COMMON-ELECTRONICE-DEVICE')], default=1, max_length=50, verbose_name='keyForm'),
            preserve_default=False,
        ),
    ]
