# Generated by Django 5.0 on 2024-01-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B2_do_dien_tu', '0009_remove_category_key_category_keyform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsb2',
            options={'ordering': ['-id'], 'verbose_name_plural': '13 - Sản phẩm bán xe cộ'},
        ),
    ]
