# Generated by Django 5.0 on 2024-01-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
                ('user_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seller_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['id'],
            },
        ),
    ]
