# Generated by Django 5.0.1 on 2024-01-04 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A4_may_moc_thiet_bi_chuyen_dung', '0001_initial'),
        ('chotot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Address_A4', to='chotot.address', verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='items',
            name='Guarantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Guarantee_A3', to='A4_may_moc_thiet_bi_chuyen_dung.guarantee', verbose_name='Bảo hành'),
        ),
        migrations.AddField(
            model_name='items',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Location_A4', to='chotot.location', verbose_name='Khu vực'),
        ),
        migrations.AddField(
            model_name='items',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_User_A4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items_image',
            name='Items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_images_Items_A4', to='A4_may_moc_thiet_bi_chuyen_dung.items'),
        ),
        migrations.AddField(
            model_name='items',
            name='Seller_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Seller_information_A4', to='A4_may_moc_thiet_bi_chuyen_dung.seller_information', verbose_name='Thông tin người bán'),
        ),
        migrations.AddField(
            model_name='items',
            name='Usage_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Usage_status_A4', to='A4_may_moc_thiet_bi_chuyen_dung.usage_status', verbose_name='Tình trạng sử dụng'),
        ),
    ]
