# Generated by Django 5.0 on 2024-01-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A3_tu_lanh_may_lanh_may_giat', '0003_category_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='key',
        ),
        migrations.AddField(
            model_name='category',
            name='keyForm',
            field=models.CharField(choices=[('FRIDGE', 'FRIDGE'), ('AIR-CONDITIONING-AIR-CONDITIONING', 'AIR-CONDITIONING-AIR-CONDITIONING'), ('WASHING-MACHINE', 'WASHING-MACHINE')], default=1, max_length=50, verbose_name='Key'),
            preserve_default=False,
        ),
    ]
