# Generated by Django 5.0.1 on 2024-01-04 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A2_nha_tot', '0001_initial'),
        ('chotot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_Address_A2', to='chotot.address', verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_Category_A2', to='A2_nha_tot.category', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='products',
            name='Interior_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_Interior_condition_A2', to='A2_nha_tot.interior_condition', verbose_name='Tình trạng nội thất'),
        ),
        migrations.AddField(
            model_name='products',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_Location_A2', to='chotot.location', verbose_name='Khu vực'),
        ),
        migrations.AddField(
            model_name='products',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_User_A2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products_image',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_image_Products_A2', to='A2_nha_tot.products'),
        ),
        migrations.AddField(
            model_name='products',
            name='Seller_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_Seller_information_A2', to='A2_nha_tot.seller_information', verbose_name='Thông tin người bán'),
        ),
    ]
