# Generated by Django 5.0 on 2024-01-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2_nha_tot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.CharField(choices=[('MOTEL-ROOM-DORMITORY', 'MOTEL-ROOM-DORMITORY'), ('WHOLE-HOUSE', 'WHOLE-HOUSE'), ('BUSINESS-PREMISES', 'BUSINESS-PREMISES')], default=1, max_length=50, verbose_name='Key'),
            preserve_default=False,
        ),
    ]
