# Generated by Django 5.0 on 2024-01-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B4_do_gia_dung_noi_that', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ParentCategory',
        ),
    ]
