# Generated by Django 5.0 on 2024-01-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4_do_gia_dung_noi_that', '0005_remove_category_parentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.CharField(choices=[('COMMON-FURNITURE-APPLIANCES', 'COMMON-FURNITURE-APPLIANCES')], default=1, max_length=50, verbose_name='Key'),
            preserve_default=False,
        ),
    ]
