# Generated by Django 5.0 on 2024-01-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4_do_gia_dung_noi_that', '0006_category_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='key',
        ),
        migrations.AddField(
            model_name='category',
            name='keyForm',
            field=models.CharField(choices=[('COMMON-FURNITURE-APPLIANCES', 'COMMON-FURNITURE-APPLIANCES')], default='', max_length=50, verbose_name='keyForm'),
            preserve_default=False,
        ),
    ]
