# Generated by Django 5.0 on 2024-01-15 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_xe_co', '0003_rename_items_itemsb1'),
        ('chotot', '0005_rename_parent_category_parentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ParentCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Parent_Category_B1', to='chotot.parentcategory', verbose_name='Danh mục cha'),
            preserve_default=False,
        ),
    ]
