# Generated by Django 5.0 on 2024-01-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_xe_co', '0006_category_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.CharField(choices=[('OTO', 'OTO'), ('XEMAY', 'XEMAY'), ('COMMON-VEHICLE', 'COMMON-VEHICLE')], max_length=50, verbose_name='Key'),
        ),
    ]
