# Generated by Django 5.0 on 2024-01-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_xe_co', '0008_alter_category_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='key',
        ),
        migrations.AddField(
            model_name='category',
            name='keyForm',
            field=models.CharField(choices=[('CAR', 'CAR'), ('MOTORBIKE', 'MOTORBIKE'), ('COMMON-VEHICLE', 'COMMON-VEHICLE')], default=1, max_length=50, verbose_name='keyForm'),
            preserve_default=False,
        ),
    ]
